### ISSUE TITLE
Rust's description is no longer accurate

### ISSUE THREAD

**Issue by zslayton** [jdm/asknot#177]
Rust's description makes reference to "4 kinds of pointers," which is no longer accurate: managed ("@") pointers have been removed from the language. Now there are only owned (~), borrowed (&) and unsafe (*).

I can make a PR for this if you can settle on a different description. Now that there are only 3 types of pointers, maybe it's a little less masochistic? :)

**Comment by xfq** [comment]
This issue was fixed in commit 7868d3df64c657051f1a7e634b82cd50fa9ac55a

**Comment by jdm** [comment]
True!
