### ISSUE TITLE
Add Mozilla Location Service

### ISSUE THREAD

**Issue by swarnava** [jdm/asknot#237]
We should add Mozilla Location service into asknot. Instead of '''what is your area of expertise?''' we can rename it to '''I love'''

*Java/Android developer can contribute to Mozilla Stumbler app which is located here: https://github.com/mozilla/MozStumbler/
*Python Developers can work on Mozilla Location website: https://github.com/mozilla/ichnaea/

Need more feedback on this! cc @hannosch @crankycoder @garvankeeley

**Comment by Mte90** [comment]
+1

**Comment by jdm** [comment]
I don't think we're emphasizing MozStumbler any more, so I'm going to go ahead and close this.
