### ISSUE TITLE
Clicking back button does not change view

### ISSUE THREAD

**Issue by varghesethomase** [jdm/asknot#249]
As seen from the attached image, going to a view and then clicking back button does not move me back to the previous view i was at. It just remains at the same view itself. To reproduce steps,
1. Go to : http://www.whatcanidoformozilla.org/#!/progornoprog/proglang
2. Go to next view by clicking Not interested. It leads to (http://www.whatcanidoformozilla.org/#!/progornoprog/support)
3. Click back button. 

Expected result: Goes back to previous 
view(http://www.whatcanidoformozilla.org/#!/progornoprog/proglang)
![screenshot from 2015-02-28 10 02 59](https://cloud.githubusercontent.com/assets/5429756/6424862/05ffb8de-bf31-11e4-8708-07a892c3eb66.png)
![screenshot from 2015-02-28 10 02 49](https://cloud.githubusercontent.com/assets/5429756/6424863/063dec26-bf31-11e4-9f83-592e2114405f.png)
![screenshot from 2015-02-28 10 04 13](https://cloud.githubusercontent.com/assets/5429756/6424864/32b47824-bf31-11e4-92cb-fb0fe64d9ac8.png)

Current. View doesnt change

**Comment by sudheesh001** [comment]
Reproducible.

**Comment by dinnu93** [comment]
It is going back in the url but those are not actual urls but section ids. The page has to reload again for every back button click.

**Comment by larryprice** [comment]
Was this addressed by #261?

**Comment by jdm** [comment]
I believe so.
