### ISSUE TITLE
Buttons break on small screen devices

### ISSUE THREAD

**Issue by sudheesh001** [jdm/asknot#260]
![img_6571](https://cloud.githubusercontent.com/assets/4545925/7977950/7f46a190-0aad-11e5-9e23-3803db09866d.PNG)

Would it be a better idea to reduce the font-size on smaller devices ?

**Comment by jdm** [comment]
Yes, that makes sense to me!

**Comment by dinnu93** [comment]
I guess this bug is cleared I checked in my android device just now. can somebody close it ?

**Comment by jdm** [comment]
I don't believe any code changes to fix this have been merged.

**Comment by dinnu93** [comment]
I don't know how but it works on my android 4.4.4
The font-size and button size are decreasing according to the screen.

**Comment by sudheesh001** [comment]
@dinnu93 I believe this has nothing to do with the android version but rather the screen size, Is your phone screen larger than that of an iPhone 5/5S/5C ? Testing it very closely, the buttons start to work fine for a width > 356

Here's the output on 356x554 screen

![screen shot 2015-06-24 at 16 01 13](https://cloud.githubusercontent.com/assets/4545925/8327976/63bc7638-1a8a-11e5-9b71-b2735b624c0b.png)

and here it is on a 320x480

![screen shot 2015-06-24 at 16 02 30](https://cloud.githubusercontent.com/assets/4545925/8327987/7d429a92-1a8a-11e5-83a9-8d1c8bd95119.png)
