### ISSUE TITLE
ffqa section doesn't appear

### ISSUE THREAD

**Issue by sviter** [jdm/asknot#268]
It seems ```<div class="group" id="ffqa">``` ("Join a Bug Day", "Use Firefox Nightly") doesn't appear on site

**Comment by sviter** [comment]
It's seems there are no "ffqa" group in this section:
```html
<div id="wrapper">
    <div class="group" id="progornoprog">
      <span class="question" data-l10n-id="progquestion"></span>
      <ul class="choices">
        <li next-group="proglang"><span data-l10n-id="writecode"></span></li>
        <li next-group="softtest"><span data-l10n-id="testsoftware"></span></li>
        <li next-group="support"><span data-l10n-id="usersupport"></span></li>
        <li next-group="translate"><span data-l10n-id="translation"></span></li>
        <li next-group="advocate"><span data-l10n-id="advocacy"></span></li>
        <li next-group="teach"><span data-l10n-id="teaching"></span></li>
        <li next-group="uxdesign"><span data-l10n-id="uxdesign"></span></li>
        <li next-group="metrics"><span data-l10n-id="metrics"></span></li>
      </ul>
    </div>
```

**Comment by jdm** [comment]
But it's in https://github.com/jdm/asknot/blob/master/index.html#L90 is it not?

**Comment by sviter** [comment]
Yes. But what about this https://github.com/jdm/asknot/blob/master/index.html#L138-L148?

**Comment by jdm** [comment]
Oh, you're right! Want to add an entry to the ffqa div for "Firefox Quality Engineering" and turn the https://github.com/jdm/asknot/blob/master/index.html#L90 into `next-group` entry that points to ffqa instead?

**Comment by sviter** [comment]
Sorry. Don't sure about result structure. Fill free to do it yourself.

**Comment by sviter** [comment]
Is am right with #269 ?
