### ISSUE TITLE
Broken link for QA of Firefox Nightly

### ISSUE THREAD

**Issue by fflorent** [jdm/asknot#270]
Hi,

The link to Firefox Nightly QA (present [here](https://quality.mozilla.org/docs/firefox/install-a-nightly-browser/)) is broken.

The broken link is: https://quality.mozilla.org/docs/firefox/install-a-nightly-browser/

For your information :)

Cheers,
Florent

**Comment by jdm** [comment]
Looks like an appropriate replacement would be https://developer.mozilla.org/en-US/docs/Mozilla/QA/How_can_I_help_test_#Run_a_nightly_build .

**Comment by jdm** [comment]
Thanks for reporting this!

**Comment by fflorent** [comment]
You're welcome :)
