### ISSUE TITLE
Broken link for Firefox Nightly

### ISSUE THREAD

**Issue by rbillings** [jdm/asknot#271]
http://www.whatcanidoformozilla.org/?lang=ar#!/progornoprog/softtest/nightly  [repros in all languages]
the broken link is : 
https://quality.mozilla.org/docs/firefox/install-a-nightly-browser/

The original document is no longer on QMO, and was not migrated to MDN.
update link with : https://nightly.mozilla.org/

**Comment by jdm** [comment]
Whoops, looks like I didn't update after https://github.com/jdm/asknot/commit/c9faa90148aa88757360260c17ec6f08df451e2c . Any objection to the link there?

**Comment by rbillings** [comment]
I think that link is superior to going directly to Nightly- so please use that.
