### ISSUE TITLE
some help about the anatomy of this html/js of this project

### ISSUE THREAD

**Issue by luzpaz** [jdm/asknot#276]
What is the function of data-choice-id= ?

**Comment by jdm** [comment]
It's used to provide a unique id for each terminating choice in the tree. It could probably be `id` instead; I don't recall why `data-choice-id` was selected, but it might have something to do with the localization library (l10n.js).

**Comment by luzpaz** [comment]
I'm trying to figure out what happens if I change it? What impact would it have and how would i update whatever else it impacts ? I'll take a look at the localization library
