### ISSUE TITLE
Space between changes and ? in footer.

### ISSUE THREAD

**Issue by iammangod96** [jdm/asknot#279]
There must be a space between the word "change" and question mark in footer.
Instead of -
Created by Josh Matthews, Henri Koivuneva, and others. Why not make some changes?
It should be - 
Created by Josh Matthews, Henri Koivuneva, and others. Why not make some changes ?

**Comment by jdm** [comment]
Why? Is this proposed as a visual improvement, or grammatical, or something else?

**Comment by hkoivuneva** [comment]
It’s the way question marks and exclamation marks are used in India in many cases, but not in many other places around the world. Maybe we should keep it the way it is? :)





Lähettäjä: Josh Matthews
Lähetetty: ‎maanantai‎, ‎25‎. ‎tammikuuta‎ ‎2016 ‎18‎:‎25
Vast.ott: jdm/asknot





Why? Is this proposed as a visual improvement, or grammatical, or something else?
