### ISSUE TITLE
Add Firefox Devtools

### ISSUE THREAD

**Issue by nchevobbe** [jdm/asknot#286]
The site mention Firebug but not the Firefox Devtools, although Firebug is getting merged into the devtools (https://blog.getfirebug.com/2016/02/08/merging-firebug-into-the-built-in-firefox-developer-tools/)
There is a wiki page for new contributors https://developer.mozilla.org/en-US/docs/Tools/Contributing (or https://wiki.mozilla.org/DevTools/Hacking).

**Comment by jdm** [comment]
Au contraire: http://whatcanidoformozilla.org/#!/progornoprog/proglang/js/ff-js/developer-tools

**Comment by nchevobbe** [comment]
oops, sorry I missed it because it's in another group than Firebug.
Sorry about that

**Comment by jdm** [comment]
Thanks for reporting it :)
