### ISSUE TITLE
l10n-metrics contributions are no longer sought

### ISSUE THREAD

**Issue by globau** [jdm/asknot#289]
http://whatcanidoformozilla.org/#!/progornoprog/metrics/l10n-metrics directs users to https://wiki.mozilla.org/Foundation/Metrics/Contribute which now states "I'm leaving Mozilla, and haven't had time to successfully maintain this contribution project so I've taken down the contents of this page".

that option should be removed from wcidfm.

**Comment by jdm** [comment]
Thanks for the report!
