### ISSUE TITLE
The redirected link to webmaker does not work

### ISSUE THREAD

**Issue by harshithachidanand** [jdm/asknot#290]
The link redirected on clicking "Tell me more" in webmaker does not work
(https://webmaker.org/en-US/mentor).
I thought it makes more sense to redirect to https://webmaker.org/

The following file does just that
[index.html.zip](https://github.com/jdm/asknot/files/315485/index.html.zip)

Every line of code except this remains the same

Thanks :)

**Comment by JeanPaulLucien** [comment]
I see 404 error on the mentor page.

**Comment by jdm** [comment]
Should be fixed now.
