### ISSUE TITLE
Update the Coding section

### ISSUE THREAD

**Issue by rwakulszowa** [jdm/asknot#298]
Hey, I don't know if this site is still maintained, but if it is, there are some outdated links which probably can be removed:
- [x] https://github.com/mozilla/shumway - last commit in March
- [x] https://github.com/mozilla/persona - last commit in March
- [x] https://github.com/mozilla/popcorn-js - last commit in June 2015
- [x] https://github.com/mozilla/loop - shutdown

There are some new projects which could be added, those are the ones I've found, but I guess there's more
- [ ] https://github.com/mozilla/thimble.mozilla.org - JS
- [ ] https://github.com/mozilla/tofino - JS
- [ ] https://testpilot.firefox.com/experiments - JS
- [ ] https://github.com/mozilla-services/pageshot/ - JS
- [ ] https://github.com/mozilla/universal-search - JS
- [ ] https://github.com/internetarchive/FirefoxNoMore404s - JS
- [ ] https://github.com/bwinton/TabCenter - JS
- [ ] https://github.com/mozilla/activity-stream - JS
- [ ] https://github.com/mozilla/blok/ - JS
- [ ] https://github.com/meandavejustice/min-vid - JS

I can try to update the relevant files, but I've decided to ask if it even makes sense first.

**Comment by jdm** [comment]
Getting rid of shumway and persona make sense. Emscripten is separate  from and not replaced by binaeyen. We'll need to think about whether it makes sense to add the project's you mention, since they may not be ready to deal with new contributors.

**Comment by rwakulszowa** [comment]
Ok, so I've removed shumway and persona. Should I also get rid of the other 3 listed projects?
I've also listed some active projects in the previous comment.

**Comment by jdm** [comment]
Popcorn and loop, yes. Emscripten is still merging PRs, just not to the master branch right now: https://github.com/kripken/emscripten/pulls?q=is%3Apr+is%3Aclosed

**Comment by marco-c** [comment]
Would it make sense to share the projects between bugsahoy and here? This way every time we add a project on bugsahoy, it shows up here too.

**Comment by jdm** [comment]
Historically I've tried to curate the list of projects here so that they have an actual landing page with explanatory text. That's not always the case with the projects listed on bugsahoy.

**Comment by austinprog** [comment]
@jdm @marco-c  @rwakulszowa Is this still active? I would like to work on this if it is. Thanks

**Comment by jdm** [comment]
@austinprog It is still active.

**Comment by jdm** [comment]
That being said, the projects linked in the original comment do not look active, so I'm actually going to go ahead and close this.
