### ISSUE TITLE
Remove Firebug

### ISSUE THREAD

**Issue by SebastianZ** [jdm/asknot#301]
Firebug is officially [merged into the Devtools](https://blog.getfirebug.com/2016/06/07/unifying-firebug-firefox-devtools/), which means the extension development is discontinued.

Therefore it should be removed from the suggestions.

Sebastian

**Comment by SebastianZ** [comment]
Thank you for the fast change!
I assume it may also be removed from https://github.com/jdm/asknot/blob/4a7ba2a719df4944089142bfc8ba3fb91e6390a3/locales/en.ini#L65.

Sebastian

**Comment by jdm** [comment]
Yep, and other locales too.
