### ISSUE TITLE
Get new mozilla logo + style

### ISSUE THREAD

**Issue by pascalchevrel** [jdm/asknot#313]
We have a new logo, although the Zilla font is not available yet to use it directly, the logo is available as svg.

We should also use the Fira Sans font and no longer Open Sans.

**Comment by hkoivuneva** [comment]
I like the new logo and design language a lot! Very impressive. They indeed feel more open, welcoming, they embrace the web but also are a part of it and a part of creating it... This can be a good opportunity for us to play with it to create a new asknot experience using the new guidelines. It would be great to create a logo for asknot following them too, with the Zilla font when it comes available.

**Comment by pascalchevrel** [comment]
![capture d ecran - 2017-01-21 a 10 10 09](https://cloud.githubusercontent.com/assets/454375/22173403/e6ac9a84-dfc1-11e6-8294-77c1a39e77c5.png)

This is what the PR for this issue gives.

**Comment by pascalchevrel** [comment]
How about something like that with a very light top bar and a blue logo?
![capture d ecran - 2017-01-23 a 20 45 53](https://cloud.githubusercontent.com/assets/454375/22219959/17a520b0-e1ad-11e6-936f-f12611fe1c50.png)

**Comment by JeanPaulLucien** [comment]
Why do you want to repair that didn't break? 
Stay actually design and change logo.

**Comment by pascalchevrel** [comment]
OK, it seems that we are not allowed to use other solid colors than black and white for the logo (the final guidelines are not published yet but I pinged people at marketing). Please hold on a bit on this one until I update my PR.

**Comment by polyzen** [comment]
This appears to be resolved.
