### ISSUE TITLE
TypeError: choices[(choices.length - 1)] is undefined

### ISSUE THREAD

**Issue by JeanPaulLucien** [jdm/asknot#316]
`function investigate(ev) {
        if(ev.which === 2) {
          return;
        }
        ev.preventDefault();
        var choice = $('.choices li', groupNode)[choices[choices.length - 1][choiceIndex[choiceIndex.length - 1]]];
        if (choice.hasAttribute('next-group')) {
            cleanUpCurrent();
            switchGroup(choice.getAttribute('next-group'));
        } else {
            window.open(choice.getAttribute('target'));
        }
    }`
When I go to the website or reload it, I have this errors and central button doesn't show. If I press "It wrong...", the website starts to work well.

**Comment by jdm** [comment]
What is the url you visit when you see this error?

**Comment by JeanPaulLucien** [comment]
https://whatcanidoformozilla.org - start page

**Comment by jdm** [comment]
What language does the page default to?

**Comment by JeanPaulLucien** [comment]
English.

**Comment by pascalchevrel** [comment]
I can't reproduce, Jean-Paul what browser version are you using ?

**Comment by JeanPaulLucien** [comment]
`Синхронный XMLHttpRequest в основной нити является устаревшим из-за его пагубного влияния на работу конечного пользователя. Для получения дополнительной помощи обратитесь к http://xhr.spec.whatwg.org/
 l10n.js:193:0
Error: Syntax error, unrecognized expression: #lang option[value=]
 jquery-1.11.2.min.js:2:12717
TypeError: choiceIndex[(choiceIndex.length - 1)] is undefined
 foopy.js:123:22
TypeError: choiceIndex[(choiceIndex.length - 1)] is undefined
 foopy.js:123:22
TypeError: lastIndex is undefined
 foopy.js:50:26
TypeError: choices[(choices.length - 1)] is undefined
 foopy.js:50:26
TypeError: choices[(choices.length - 1)] is undefined
 foopy.js:123:22`

Cyberfox 42.0x64

I watched the code. I'm not sure, but do you really use an empty array without basic numbers, with var which generates from other generate vars?

**Comment by JeanPaulLucien** [comment]
`Синхронный XMLHttpRequest в основной нити является устаревшим из-за его пагубного влияния на работу конечного пользователя. Для получения дополнительной помощи обратитесь к http://xhr.spec.whatwg.org/
 l10n.js:193:0
Error: Syntax error, unrecognized expression: #lang option[value=]
 jquery-1.11.2.min.js:2:12717
TypeError: choiceIndex[(choiceIndex.length - 1)] is undefined
 foopy.js:123:22
TypeError: choiceIndex[(choiceIndex.length - 1)] is undefined
 foopy.js:123:22
TypeError: lastIndex is undefined
 foopy.js:50:26
TypeError: choices[(choices.length - 1)] is undefined
 foopy.js:50:26
TypeError: choices[(choices.length - 1)] is undefined
 foopy.js:123:22`

Cyberfox 42.0x64

I watched the code. I'm not sure, but do you really use an empty array without basic numbers, with var which generates from other generate vars?

**Comment by jdm** [comment]
I recommend updating to Cyberfox 51 and seeing if it still occurs.
