### ISSUE TITLE
No project for golang?

### ISSUE THREAD

**Issue by JunoJunho** [jdm/asknot#326]
I cannot find a project written in golang.

When I clicked to see projects written in golang, the service took me a former page.

Is something wrong? or is everything correctly working?

**Comment by jdm** [comment]
Whoops, we should have removed the Go category entirely in #323. I'm not aware of any other Go projects created by Mozilla. Would you like to make a pull request to remove it from index.html?

**Comment by JunoJunho** [comment]
I make it. :)

**Comment by jdm** [comment]
Fixed in #327.
