### ISSUE TITLE
Add Firefox Focus to project options

### ISSUE THREAD

**Issue by ekager** [jdm/asknot#344]
Great first open source projects! 
• Firefox Focus for iOS (Swift) https://github.com/mozilla-mobile/focus-ios
• Firefox Focus for Android (Java) https://github.com/mozilla-mobile/focus-android

**Comment by jdm** [comment]
Would you like to make a PR? It requires adding an entry to the [Swift](https://github.com/jdm/asknot/blob/master/index.html#L221-L223) and [Java](https://github.com/jdm/asknot/blob/master/index.html#L325-L331) groups, as well as adding corresponding new [English strings](https://github.com/jdm/asknot/blob/master/locales/en.ini).

**Comment by ekager** [comment]
Thanks for the point in the right direction @jdm ! Created a PR with the additions
