### ISSUE TITLE
The mozilla logo on top left should be a hyperlink

### ISSUE THREAD

**Issue by aaryandewan** [jdm/asknot#363]
The mozilla logo on the [homepage](https://www.whatcanidoformozilla.org/#!/progornoprog/proglang) should redirect you to [mozilla.org](https://mozilla.org).

**Comment by rexj8** [comment]
Hello sir, I am just entering in this world open source projects. Can you allow me to contribute in this project.

**Comment by rexj8** [comment]
I am currently pursuing B.Tech and learning Web Dev

**Comment by krsrv** [comment]
#365 should be the proper pull request link for this

**Comment by rexj8** [comment]
[#368 ](url) making mozilla logo path hyperlink done

**Comment by jdm** [comment]
Fixed by #365.
