### ISSUE TITLE
useradvocacy should be removed

### ISSUE THREAD

**Issue by bjherbison** [jdm/asknot#369]
The entry for useradvocacy points to https://wiki.mozilla.org/Advocacy . That page hasn't been updated since 2015. I tried to contact the six e-mail addresses on the page and five no longer work. Ilana Segall responded and said the page can be removed.

Before removing the wiki page we should remove the entry on whatcanidoformozilla.org .

**Comment by bjherbison** [comment]
I have local changes for this but it doesn't look like I have permissions to create a branch on github.com for this repository.

I've read documentation (most recently https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-and-deleting-branches-within-your-repository ) but I don't see the Create branch option so I believe this is a permission issue.

(I've used git before, but never GitHub.)

**Comment by jdm** [comment]
On github the process requires forking a repository, making the change in a branch on your fork, then making a pull request to the original repository.

**Comment by jdm** [comment]
I've gone ahead and removed it. Thanks!
